# Здесь укажи какие нормализованные события (одно или несколько) ты подаешь на вход правилу корреляции.
# События отделяются друг от друга символом новой строки. Каждое их них должно быть записано в строку.
# Здесь укажи какие нормализованные события (одно или несколько) ты подаешь на вход правилу корреляции.
# События отделяются друг от друга символом новой строки. Каждое их них должно быть записано в строку.
{"action":"start","category.generic":"Process","category.high":"Availability Management","category.low":"Control","chain_id":"7035","datafield1":"python3","datafield2":"root","datafield3":",755","datafield4":"/usr/bin/python3.12","event_src.category":"Operating system","event_src.ip":"127.0.0.1","event_src.rule":"process_creation","event_src.subsys":"auditd","event_src.title":"unix_like","id":"PT_UNIX_like_auditd_syslog_structured_syscall_process_start","importance":"low","logon_service":"pts/0","msgid":"execve","object":"process","object.account.group":"user","object.account.id":"user","object.account.name":"user","object.process.cmdline":"python3 copy_fail_exp.py","object.process.cwd":"/home/user/Desktop/copy-fail-CVE-2026-31431","object.process.fullpath":"/usr/bin/python3","object.process.id":"4882","object.process.meta":"python3 copy_fail_exp.py","object.process.name":"python3","object.process.parent.id":"4858","object.process.path":"/usr/bin/","status":"success","subject":"account","subject.account.id":"user","subject.account.name":"user","subject.account.privileges":"user","subject.account.session_id":"3","time":"2026-03-10T14:36:10.000Z"}
{"action":"create","category.generic":"Socket","category.high":"Network Management","category.low":"Manipulation","chain_id":"7036","datafield1":"python3","event_src.category":"Operating system","event_src.ip":"127.0.0.1","event_src.rule":"af_alg","event_src.subsys":"auditd","event_src.title":"unix_like","id":"PT_UNIX_like_auditd_syslog_structured_syscall_sockets","importance":"low","logon_service":"pts/0","msgid":"socket","object":"socket","object.account.group":"user","object.account.id":"user","object.account.name":"user","object.domain":"alg","object.type":"SOCK_SEQPACKET","status":"success","subject":"process","subject.account.id":"user","subject.account.name":"user","subject.account.privileges":"user","subject.account.session_id":"3","subject.process.fullpath":"/usr/bin/python3.12","subject.process.id":"4882","subject.process.meta":"python3 copy_fail_exp.py","subject.process.name":"python3.12","subject.process.parent.id":"4858","subject.process.path":"/usr/bin/","time":"2026-03-10T14:36:10.000Z"}
{"action":"assign","category.generic":"Socket","category.high":"Network Management","category.low":"Manipulation","chain_id":"7037","datafield1":"python3","event_src.category":"Operating system","event_src.ip":"127.0.0.1","event_src.rule":"af_alg","event_src.subsys":"auditd","event_src.title":"unix_like","id":"PT_UNIX_like_auditd_syslog_structured_syscall_sockets","importance":"low","logon_service":"pts/0","msgid":"bind","object":"socket","object.account.group":"user","object.account.id":"user","object.account.name":"user","object.property":"socket_domain","status":"success","subject":"process","subject.account.id":"user","subject.account.name":"user","subject.account.privileges":"user","subject.account.session_id":"3","subject.process.fullpath":"/usr/bin/python3.12","subject.process.id":"4882","subject.process.meta":"python3 copy_fail_exp.py","subject.process.name":"python3.12","subject.process.parent.id":"4858","subject.process.path":"/usr/bin/","time":"2026-03-10T14:36:10.000Z"}
{"action":"modify","category.generic":"Socket","category.high":"Network Management","category.low":"Manipulation","chain_id":"7038","datafield1":"python3","event_src.category":"Operating system","event_src.ip":"127.0.0.1","event_src.rule":"af_alg","event_src.subsys":"auditd","event_src.title":"unix_like","id":"PT_UNIX_like_auditd_syslog_structured_syscall_sockets","importance":"low","logon_service":"pts/0","msgid":"setsockopt","object":"socket","object.account.group":"user","object.account.id":"user","object.account.name":"user","object.property":"socket_option","object.value":"SOL_ALG:0x1","status":"success","subject":"process","subject.account.id":"user","subject.account.name":"user","subject.account.privileges":"user","subject.account.session_id":"3","subject.process.fullpath":"/usr/bin/python3.12","subject.process.id":"4882","subject.process.meta":"python3 copy_fail_exp.py","subject.process.name":"python3.12","subject.process.parent.id":"4858","subject.process.path":"/usr/bin/","time":"2026-03-10T14:36:10.000Z"}
{"action":"modify","category.generic":"Socket","category.high":"Network Management","category.low":"Manipulation","chain_id":"7039","datafield1":"python3","event_src.category":"Operating system","event_src.ip":"127.0.0.1","event_src.rule":"af_alg","event_src.subsys":"auditd","event_src.title":"unix_like","id":"PT_UNIX_like_auditd_syslog_structured_syscall_sockets","importance":"low","logon_service":"pts/0","msgid":"setsockopt","object":"socket","object.account.group":"user","object.account.id":"user","object.account.name":"user","object.property":"socket_option","object.value":"SOL_ALG:0x5","status":"success","subject":"process","subject.account.id":"user","subject.account.name":"user","subject.account.privileges":"user","subject.account.session_id":"3","subject.process.fullpath":"/usr/bin/python3.12","subject.process.id":"4882","subject.process.meta":"python3 copy_fail_exp.py","subject.process.name":"python3.12","subject.process.parent.id":"4858","subject.process.path":"/usr/bin/","time":"2026-03-10T14:36:10.000Z"}
{"action":"start","category.generic":"Process","category.high":"Availability Management","category.low":"Control","chain_id":"7196","datafield1":"sh","datafield2":"root","datafield3":",755","datafield4":"/usr/bin/dash","event_src.category":"Operating system","event_src.ip":"127.0.0.1","event_src.rule":"process_creation","event_src.subsys":"auditd","event_src.title":"unix_like","id":"PT_UNIX_like_auditd_syslog_structured_syscall_process_start","importance":"low","logon_service":"pts/0","msgid":"execve","object":"process","object.account.group":"user","object.account.id":"user","object.account.name":"user","object.process.cmdline":"sh -c -- su","object.process.cwd":"/home/user/Desktop/copy-fail-CVE-2026-31431","object.process.fullpath":"/bin/sh","object.process.id":"4883","object.process.meta":"sh -c -- su","object.process.name":"sh","object.process.parent.id":"4882","object.process.path":"/bin/","status":"success","subject":"account","subject.account.id":"user","subject.account.name":"user","subject.account.privileges":"user","subject.account.session_id":"3","time":"2026-03-10T14:36:10.000Z"}
{"action":"start","category.generic":"Process","category.high":"Availability Management","category.low":"Control","chain_id":"7197","datafield1":"su","datafield2":"root","datafield3":",755","datafield4":"/usr/bin/su","event_src.category":"Operating system","event_src.ip":"127.0.0.1","event_src.rule":"process_creation","event_src.subsys":"auditd","event_src.title":"unix_like","id":"PT_UNIX_like_auditd_syslog_structured_syscall_process_start","importance":"low","logon_service":"pts/0","msgid":"execve","object":"process","object.account.group":"user","object.account.id":"root","object.account.name":"root","object.process.cmdline":"su","object.process.cwd":"/home/user/Desktop/copy-fail-CVE-2026-31431","object.process.fullpath":"/usr/bin/su","object.process.id":"4884","object.process.meta":"su","object.process.name":"su","object.process.parent.id":"4883","object.process.path":"/usr/bin/","status":"success","subject":"account","subject.account.id":"user","subject.account.name":"user","subject.account.privileges":"root","subject.account.session_id":"3","time":"2026-03-10T14:36:10.000Z"}
{"action":"start","category.generic":"Process","category.high":"Availability Management","category.low":"Control","chain_id":"7198","datafield1":"sh","datafield2":"root","datafield3":",755","datafield4":"/usr/bin/dash","event_src.category":"Operating system","event_src.ip":"127.0.0.1","event_src.rule":"process_creation","event_src.subsys":"auditd","event_src.title":"unix_like","id":"PT_UNIX_like_auditd_syslog_structured_syscall_process_start","importance":"low","logon_service":"pts/0","msgid":"execve","object":"process","object.account.group":"user","object.account.id":"root","object.account.name":"root","object.process.cwd":"/home/user/Desktop/copy-fail-CVE-2026-31431","object.process.fullpath":"/bin/sh","object.process.id":"4884","object.process.meta":"su","object.process.name":"sh","object.process.parent.id":"4883","object.process.path":"/bin/","status":"success","subject":"account","subject.account.id":"user","subject.account.name":"user","subject.account.privileges":"root","subject.account.session_id":"3","time":"2026-03-10T14:36:10.000Z"}
{"action":"start","category.generic":"Process","category.high":"Availability Management","category.low":"Control","chain_id":"7199","datafield1":"id","datafield2":"root","datafield3":",755","datafield4":"/usr/bin/id","event_src.category":"Operating system","event_src.ip":"127.0.0.1","event_src.rule":"process_creation","event_src.subsys":"auditd","event_src.title":"unix_like","id":"PT_UNIX_like_auditd_syslog_structured_syscall_process_start","importance":"low","logon_service":"pts/0","msgid":"execve","object":"process","object.account.group":"user","object.account.id":"root","object.account.name":"root","object.process.cmdline":"id","object.process.cwd":"/home/user/Desktop/copy-fail-CVE-2026-31431","object.process.fullpath":"/usr/bin/id","object.process.id":"4885","object.process.meta":"id","object.process.name":"id","object.process.parent.id":"4884","object.process.path":"/usr/bin/","status":"success","subject":"account","subject.account.id":"user","subject.account.name":"user","subject.account.privileges":"root","subject.account.session_id":"3","time":"2026-03-10T14:36:13.000Z"}

# Вход легитимный "в рамках" одной сессии
{"action":"elevate","category.generic":"Account","category.high":"Users And Rights Management","category.low":"Manipulation","chain_id":"5446","event_src.category":"Operating system","event_src.hostname":"ubnuser","event_src.subsys":"auditd","event_src.title":"unix_like","id":"PT_UNIX_like_auditd_syslog_structured_user_auth","importance":"low","logon_service":"pts/1","msgid":"USER_AUTH","object":"account","object.account.name":"root","status":"ongoing","subject":"account","subject.account.id":"1000","subject.account.name":"user","subject.account.session_id":"3","subject.process.fullpath":"/usr/bin/su","subject.process.id":"3445","subject.process.name":"su","subject.process.path":"/usr/bin/","time":"2026-03-10T14:36:13.000Z"}


# Тут будет твой модульный тест.
# Пример:
## создать для теста временную БД с табличными списками
# table_list default
## ожидаемое заполнение табличных списков
# table_list {"AD_Domain_Controllers":[{"ip":"8.8.8.8","hostname":"dc.contoso.com"}]}
## ожидаеммые события
# expect <число>|not|any {<через запятую пары "поле":"значение">}
    
table_list default
table_list {}
expect 0 {"correlation_name":"CVE_2026_31431_Copy_fail"}