# Здесь укажи какие нормализованные события (одно или несколько) ты подаешь на вход правилу корреляции.
# События отделяются друг от друга символом новой строки. Каждое их них должно быть записано в строку.
# Здесь укажи какие нормализованные события (одно или несколько) ты подаешь на вход правилу корреляции.
# События отделяются друг от друга символом новой строки. Каждое их них должно быть записано в строку.
{"action":"detect","category.generic":"Connection","category.high":"Network Interaction Management","category.low":"State","direction":"ingress","dst.fqdn":"dc01.work.local","dst.hostname":"dc01","dst.ip":"192.168.0.10","dst.port":445,"event_src.category":"Other","event_src.fqdn":"dc01.work.local","event_src.hostname":"dc01","event_src.rule":"-","event_src.subsys":"Microsoft-Windows-Sysmon/Operational","event_src.title":"sysmon","event_src.vendor":"microsoft","id":"PT_Microsoft_Windows_eventlog_Sysmon_3_Network_connection","importance":"info","msgid":"3","object":"connection","object.account.domain":"nt authority","object.account.id":"synthetic:система@nt authority","object.account.name":"система","object.process.fullpath":"system","object.process.guid":"0d1d3b46-ecbd-6a19-eb03-000000000000","object.process.id":"4","object.process.name":"system","protocol":"tcp","src.hostname":"-","src.ip":"192.168.0.30","src.port":55560,"status":"success","subject":"rule","subject.name":"-","time":"2026-05-29T20:23:51.648Z"}
{"action":"detect","category.generic":"Connection","category.high":"Network Interaction Management","category.low":"State","direction":"egress","dst.hostname":"-","dst.ip":"192.168.0.30","dst.port":445,"event_src.category":"Other","event_src.fqdn":"dc01.work.local","event_src.hostname":"dc01","event_src.rule":"-","event_src.subsys":"Microsoft-Windows-Sysmon/Operational","event_src.title":"sysmon","event_src.vendor":"microsoft","id":"PT_Microsoft_Windows_eventlog_Sysmon_3_Network_connection","importance":"info","msgid":"3","object":"connection","object.account.domain":"nt authority","object.account.id":"synthetic:система@nt authority","object.account.name":"система","object.process.fullpath":"system","object.process.guid":"0d1d3b46-ecbd-6a19-eb03-000000000000","object.process.id":"4","object.process.name":"system","protocol":"tcp","src.fqdn":"dc01.work.local","src.hostname":"dc01","src.ip":"192.168.0.10","src.port":49359,"status":"success","subject":"rule","subject.name":"-","time":"2026-05-29T20:23:51.668Z"}
{"action":"bind","event_src.category":"Other","event_src.fqdn":"dc01.work.local","event_src.hostname":"dc01","event_src.rule":"-","event_src.subsys":"Microsoft-Windows-Sysmon/Operational","event_src.title":"sysmon","event_src.vendor":"microsoft","id":"PT_Microsoft_Windows_eventlog_Sysmon_18_Pipe_connected","importance":"info","msgid":"18","object":"resource","object.name":"lsass","object.type":"pipe","status":"success","subject":"process","subject.account.domain":"nt authority","subject.account.id":"synthetic:система@nt authority","subject.account.name":"система","subject.process.fullpath":"system","subject.process.guid":"0d1d3b46-ecbd-6a19-eb03-000000000000","subject.process.id":"4","subject.process.name":"system","subject.process.path":"","time":"2026-05-29T20:23:51.673Z"}
{"action":"login","category.generic":"Operating System","category.high":"Access Management","category.low":"Communication","chain_id":"d6b97281-efa2-0001-e372-b9d6a2efdc01","datafield6":"Network","datafield9":"NTLM","dst.fqdn":"desktop-iab210v.work.local","dst.hostname":"desktop-iab210v","event_src.category":"AAA","event_src.fqdn":"desktop-iab210v.work.local","event_src.hostname":"desktop-iab210v","event_src.subsys":"Security","event_src.title":"windows","event_src.vendor":"microsoft","id":"PT_Microsoft_Windows_eventlog_4624_An_account_was_successfully_logged_on","importance":"info","logon_auth_method":"remote","logon_service":"NtLmSsp","logon_type":3,"msgid":"4624","object":"system","object.property":"session ID with ElevatedToken","object.value":"0","src.hostname":"dc01","src.ip":"192.168.0.30","src.port":38536,"status":"success","subject":"account","subject.account.domain":"work","subject.account.id":"S-1-5-21-2790878447-3455683389-983535108-1002","subject.account.name":"dc01$","subject.account.privileges":"local administrator rights","subject.account.session_id":"5350590","time":"2026-05-29T20:23:51.688Z"}
{"action":"login","category.generic":"Operating System","category.high":"Access Management","category.low":"Communication","datafield6":"Network","datafield9":"NTLM","dst.fqdn":"dc01.work.local","dst.hostname":"dc01","event_src.category":"AAA","event_src.fqdn":"dc01.work.local","event_src.hostname":"dc01","event_src.subsys":"Security","event_src.title":"windows","event_src.vendor":"microsoft","id":"PT_Microsoft_Windows_eventlog_4624_An_account_was_successfully_logged_on","importance":"info","logon_auth_method":"remote","logon_service":"NtLmSsp","logon_type":3,"msgid":"4624","object":"system","src.ip":"192.168.0.30","src.port":55560,"status":"success","subject":"account","subject.account.domain":"nt authority","subject.account.id":"S-1-5-7","subject.account.name":"анонимный вход","subject.account.session_id":"895532","time":"2026-05-29T20:23:51.657Z"}




# Тут будет твой модульный тест.
# Пример:
## создать для теста временную БД с табличными списками
# table_list default
## ожидаемое заполнение табличных списков
# table_list {"AD_Domain_Controllers":[{"ip":"8.8.8.8","hostname":"dc.contoso.com"}]}
## ожидаеммые события
# expect <число>|not|any {<через запятую пары "поле":"значение">}
    
table_list default
table_list {}
expect 1 {"correlation_name":"NTLM_Relay_Lateral_Movement"}